namespace Voiceover.Client.Models;

public record AuthResponse(string Token, DateTime ExpiresAtUtc, string RefreshToken, int UserId, string Username, string? AvatarUrl = null);
public record GuildServerResponse(int Id, string Name, string? IconUrl, int OwnerId);
public record SetIconRequest(string Url);
public record ChannelResponse(int Id, string Name, string Type, int GuildServerId, int Position);
public record MessageResponse(int Id, string Content, int ChannelId, int AuthorId, string AuthorUsername, DateTime SentAt, string? AttachmentUrl = null, string? AuthorAvatarUrl = null, DateTime? EditedAt = null);
public record EditMessageRequest(string Content);
public record DirectMessageResponse(int Id, string Content, int SenderId, int RecipientId, DateTime SentAt, DateTime? EditedAt = null);
public record DmConversationResponse(int OtherUserId, string OtherUsername, string LastMessagePreview, DateTime LastMessageAt, string? OtherUserAvatarUrl = null);
public record SetKeyMaterialRequest(string PublicKey, string WrappedPrivateKey, string PrivateKeySalt);
public record PublicKeyResponse(int UserId, string? PublicKey);
public record OwnKeyMaterialResponse(string? PublicKey, string? WrappedPrivateKey, string? PrivateKeySalt);
public record SetServerKeyRequest(string WrappedKey);
public record ServerKeyResponse(string? WrappedKey, int? WrappedByUserId);
public record UserSummaryResponse(int Id, string Username, string? AvatarUrl = null);
public record InviteResponse(string Code, DateTime? ExpiresAt, int? MaxUses, int UseCount);
public record MemberResponse(int UserId, string Username, string Role, string? AvatarUrl = null, string PresenceState = "Offline");
public record UploadResponse(string Url);
public record VoiceParticipant(int UserId, string Username, string? AvatarUrl = null);
public record ChannelVoiceRoster(int ChannelId, List<VoiceParticipant> Members);
public record SetAvatarRequest(string Url);
public record FriendResponse(int UserId, string Username, string? AvatarUrl = null, string PresenceState = "Offline");
public record FriendRequestResponse(int Id, int UserId, string Username, string Direction, string? AvatarUrl = null);
public record LiveKitJoinResponse(string Token, string ServerUrl);
public record VersionInfo(string Version, string InstallerUrl, string PortableUrl);
